name: Build Zip CI

on:
  push:
    branches: [ 'master' ]
  pull_request: 
    branches: [ 'master' ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install dependencies for build (Apt)
      shell: bash
      run: |
        sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
        sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libarchive-tools curl jq tree
    - name: Build Zip x64
      shell: bash
      env:
        ARCH: 'x64'
        OUT_ZIP: 'NOIR.zip'
      run: make -e && tree
    - name: Build Zip ARM64
      shell: bash
      env:
        ARCH: 'arm64'
        OUT_ZIP: 'NOIR_arm64.zip'
      run: make -e && tree
    - name: Upload a Build Artifact x64
      uses: actions/upload-artifact@main
      with:
        name: NOIR.zip
        path: ./NOIR.zip
    - name: Upload a Build Artifact ARM64
      uses: actions/upload-artifact@main
      with:
        name: NOIR_arm64.zip
        path: ./NOIR_arm64.zip
